services:
  fa3st-registry:
    image: eclipsefa3st/fa3st-registry
    volumes:
      - ../examples/:/app/resources/
    environment:
      - spring.profiles.active=jpa
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.datasource.driver=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=admin
      - service.port=8090
    ports:
      - 8090:8090
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 8092:5432